name: torch-scene
channels:
  - pytorch
  - defaults
dependencies:
  - pip:
    - pandas==1.4.2
    # - pytorch==1.11.0
    # - torchvision==0.12.0
    - numpy==1.21.5
    - pip==21.2.4
    - pillow==9.0.1
    # - cudatoolkit==11.3.1
    - ipykernel
    - hydra-core==1.2.0
    - omegaconf==2.2.2
    - torchmetrics==0.9.0
    - matplotlib
    - tpot
    # - tensorboard==2.7.0
    # - tensorboard-data-server==0.6.1
    # - tensorboard-plugin-wit==1.8.0